image: Visual Studio 2017
clone_folder: c:\openpose

shallow_clone: true

environment:
  global:
    OPENPOSE_ROOT: "%APPVEYOR_BUILD_FOLDER%\\bin\\nmake\\release"
    OPENCL_ROOT: "%APPVEYOR_BUILD_FOLDER%\\bin\\opencl"
    OPENCL_REGISTRY: "https://www.khronos.org/registry/cl"

install:
  - echo Installing OpenCL
  - ps: mkdir $env:OPENCL_ROOT
  - ps: pushd $env:OPENCL_ROOT
  - ps: $opencl_registry = $env:OPENCL_REGISTRY
  # This downloads the source to the Khronos ICD library
  - git clone --depth 1 https://github.com/KhronosGroup/OpenCL-ICD-Loader.git
  - ps: mv ./OpenCL-ICD-Loader/* .
  # This downloads all the opencl header files
  # The cmake build files expect a directory called inc
  - ps: mkdir inc/CL_headers_repo
  - git clone --depth 1 https://github.com/KhronosGroup/OpenCL-Headers.git inc/CL_headers_repo
  - ps: pushd inc
  - ps: mkdir CL
  - ps: cp CL_headers_repo/opencl22/CL/* CL/
  - ps: popd
  # - ps: wget $opencl_registry/api/2.1/cl.hpp -OutFile inc/CL/cl.hpp
  # - ps: dir; if( $lastexitcode -eq 0 ){ dir include/CL } else { Write-Output boom }
  # Create the static import lib in a directory called lib, so findopencl() will find it
  - ps: mkdir lib
  - ps: pushd lib
  - cmake -G "NMake Makefiles" ..
  - nmake
  - ps: mkdir x64; cp OpenCL.lib x64\
  - ps: popd
  # Switch to OpenCL 1.2 headers
  - ps: pushd inc/CL
  - ps: del *
  - ps: cp -r ../CL_headers_repo/opencl12/CL/* .
  # - git fetch origin opencl12:opencl12
  # - git checkout opencl12
  - ps: popd
  # Rename the inc directory to include, so FindOpencl() will find it
  - ps: ren inc include
  - ps: popd
 
build_script:
    - mkdir build
    - cd build
    - cmake -DGPU_MODE=OPENCL -G "Visual Studio 15 2017 Win64" ..
    - cmake --build . --config "Release"

after_build:
    - ps: cd ..
    - ps: mkdir artifacts
    - ps: mkdir artifacts/bin
    - ps: mkdir artifacts/examples
    - ps: mkdir artifacts/examples/media
    - ps: mkdir artifacts/include
    - ps: mkdir artifacts/lib
    - ps: Get-ChildItem -Path build/x64/Release/*.exe -Recurse -File | Copy-Item -Destination artifacts/bin
    - ps: Get-ChildItem -Path build/x64/Release/*.dll -Recurse -File | Copy-Item -Destination artifacts/bin
    - ps: Get-ChildItem -Path build/bin/*.dll -Recurse -File | Copy-Item -Destination artifacts/bin
    - ps: Get-ChildItem -Path examples/media/* -Recurse -File | Copy-Item -Destination artifacts/examples/media
    - ps: Copy-Item include/openpose -Recurse -Destination artifacts/include/
    - ps: Copy-Item 3rdparty/windows/opencv/include/opencv2 -Recurse -Destination artifacts/include/
    - ps: Get-ChildItem -Path build/*.lib -Recurse -File | Copy-Item -Destination artifacts/lib
    - ps: Get-ChildItem -Path 3rdparty/*.lib -Recurse -File | Copy-Item -Destination artifacts/lib
    - ps: Copy-Item models -Recurse -Destination artifacts/
    - ps: cd artifacts
    - ps: 7z a ..\openpose.zip .
    - ps: cd ..

artifacts:
    - path: openpose.zip
      name: OpenPose
